### ISSUE TITLE
Just a couple suggestions and some typos on the start.ipynb

### ISSUE THREAD

**Issue by cassiebreviu** [sethjuarez/pytorchintro#1]
1.	You might want to point out that the * indicates processing and a number displays once the cell has completed execution.
2.	For step one you might want to clarify that after I click launch I need to click import on the notebook to get to the start.ipynb notebook.
a.	Example: "Click the Launch button above. In the new page that opens click the “Import” button to import the notebook."
3.	Typo:  Without data we really can't do **anythin** with machine learning
a. Should be **anything**
4.	Typo:  A couple of things that **ight** seem strange when you print them out:
a. Should be **might**
5.	Typo: This is another hyperparameter that needs to be **chose**
a. Should be **chosen**
6.	Typo: way as **befor** and printing them
a. Should be **before**

**Comment by sethjuarez** [comment]
Thanks for the help!
