### ISSUE TITLE
For newer / other version of Torch need one change

### ISSUE THREAD

**Issue by SchnalzenbergerM** [sethjuarez/pytorchintro#3]
Hi Seth, I'm Mario, I'm going to present the intermediate Track of Global AI Night in Vienna. I found that the code of start.ipynb was not running in my anaconda environment. I needed to insert the following conversion in the Data-Load of the digits and test-digits line:
target_transform=transforms.Compose([
                            transforms.Lambda(lambda y: torch.zeros(10, dtype=torch.float).scatter_(0, **_torch.tensor_(y)**, 1))
                        ])
The error was somewhat cryptic "scatter_ cannot take (int, int, int)" ... so if anybody has the same issue. :)

Everything else perfect so far
Best 
Mario

**Comment by sethjuarez** [comment]
Fixed! I moved to a codespaces approach as well which should help keep me honest with versioning
